##  SECURITY
tec_ayt_portal_login:
    pattern:    /login
    defaults:   { _controller: TecAytPortalBundle:Security:error }

tec_ayt_portal_login_success:
    pattern:    /success
    defaults:   { _controller: TecAytPortalBundle:Security:success }
    
tec_ayt_portal_login_check:
    pattern:    /login/check
    
tec_ayt_portal_logout:
    pattern:    /logout

## Main
tec_ayt_portal_main_home:
    pattern:    /
    defaults:   { _controller: TecAytPortalBundle:Main:home }

tec_ayt_portal_main_about:
    pattern:    /about
    defaults:   { _controller: TecAytPortalBundle:Main:about }

tec_ayt_portal_main_contact:
    pattern:    /contact
    defaults:   { _controller: TecAytPortalBundle:Main:contact }

tec_ayt_portal_main_blog:
    pattern:    /blog
    defaults:   { _controller: TecAytPortalBundle:Main:blog }

## EVENT

tec_ayt_portal_event_list:
    pattern:    /event
    defaults:   { _controller: TecAytPortalBundle:Event:list }

## ALBUM

tec_ayt_portal_album_list:
    pattern:    /album
    defaults:   { _controller: TecAytPortalBundle:Album:list }

## CONTENT

tec_ayt_portal_content_list:
    pattern:    /content/{id}
    defaults:   { _controller: TecAytPortalBundle:Content:list }

## DOCUMENT

tec_ayt_portal_docuemt_list:
    pattern:    /document
    defaults:   { _controller: TecAytPortalBundle:Document:list }

## FORUM

tec_ayt_portal_forum_list:
    pattern:    /forum
    defaults:   { _controller: TecAytPortalBundle:Forum:list }

## USER

tec_ayt_portal_user_list:
    pattern:    /user
    defaults:   { _controller: TecAytPortalBundle:User:list }

tec_ayt_portal_user_profile:
    pattern:    /user/profile
    defaults:   { _controller: TecAytPortalBundle:User:profile }

tec_ayt_portal_user_process:
    pattern:    /user/{type}/new/{id}
    defaults:   { _controller: TecAytPortalBundle:User:process, id: 0 }
    requirements:
        id:     \d+
        type:     \d+
## DOWNLOAD
tec_ayt_portal_download:
    pattern:    /download/{id}/{class}
    defaults:   { _controller: TecAytPortalBundle:File:download }